server:
  port: 7000
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:9000/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    leyou-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务
    user-service: /user/** # 用户微服务
    auth-service: /auth/** # 授权中心微服务
  ignored-services: leyou-upload
