server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
spring:
  application:
    name: leyou-service
  profiles:
    include: datasource
mybatis:
  type-aliases-package: com.demo.pojo
  mapper-locations: classpath:com/demo/mapper/*Mapper.xml