leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: E:\IDEAProject\leyou\key\\rsa.pub # 公钥地址
    priKeyPath: E:\IDEAProject\leyou\key\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 30